// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// clean_dates_cpp
Rcpp::DataFrame clean_dates_cpp(const Rcpp::CharacterVector& input_dates);
RcppExport SEXP _fungarium_clean_dates_cpp(SEXP input_datesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type input_dates(input_datesSEXP);
    rcpp_result_gen = Rcpp::wrap(clean_dates_cpp(input_dates));
    return rcpp_result_gen;
END_RCPP
}
// clean_taxonomy_cpp
Rcpp::DataFrame clean_taxonomy_cpp(const Rcpp::CharacterVector& input_taxon_names, const Rcpp::CharacterVector& input_authority, const Rcpp::DataFrame& input_col_data);
RcppExport SEXP _fungarium_clean_taxonomy_cpp(SEXP input_taxon_namesSEXP, SEXP input_authoritySEXP, SEXP input_col_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type input_taxon_names(input_taxon_namesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type input_authority(input_authoritySEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type input_col_data(input_col_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(clean_taxonomy_cpp(input_taxon_names, input_authority, input_col_data));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fungarium_clean_dates_cpp", (DL_FUNC) &_fungarium_clean_dates_cpp, 1},
    {"_fungarium_clean_taxonomy_cpp", (DL_FUNC) &_fungarium_clean_taxonomy_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_fungarium(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
