# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

clean_dates_cpp <- function(input_dates) {
    .Call(`_fungarium_clean_dates_cpp`, input_dates)
}

clean_taxonomy_cpp <- function(input_taxon_names, input_authority, input_col_data) {
    .Call(`_fungarium_clean_taxonomy_cpp`, input_taxon_names, input_authority, input_col_data)
}

